version: 2.1

executors:
  rust:
    resource_class: small
    docker:
      - image: cimg/rust:1.59.0
jobs:
  test:
    executor: rust
    steps:
      - checkout
      - run: 
          name: Cargo test
          command: "cargo test"
workflows:
  build:
    jobs:
      - test