version: 2.1


jobs:
  test:
    docker:
      - image: cimg/rust:1.59.0
    steps:
      - checkout
      - run: 
          name: Cargo test
          command: "cargo test"
workflows:
  build:
    jobs:
      - test